### PR TITLE
Comments Bad actuator additions 

### PR DESCRIPTION
**Pull request by patrickingraham**

### CODE REVIEW

**Comment by douglase** [comment]
@kian1377 @patrickingraham what's the status of this review/PR?

**Comment by kian1377** [comment]
I have forgotten about this PR but a lot of changes have been made to Lina, including how the EFC jacobian is generated because I implemented the `build_jacobian()` method in a way that will let us use different modal basis the way we do for iEFC. 

I think the best way to implement a bad actuator would be to implement it solely in the model. By that I mean, when the model is given an actuator command, it should apply that command to all actuators except for the bad actuator(s) that are either fixed or floating. This would be more realistic as it is what is done on the testbed, so that is what I think we should do moving forward.

**Comment by patrickingraham** [comment]
I think the information that was useful in this PR was the documentation of the code... if Kian implemented those docs elsewhere then this can be closed without merging.

**Comment by kian1377** [comment]
So I am working on the docstrings in the code some more and just made a pull request adding some of them to the main branch, but I agree this PR should be closed and we should make issues for missing docstrings (of which there are still plenty but I discovered a VScode extension that generates them automatically so I will get to them in the coming weeks).

**Pull request closed without merging**
